frr version 10.5
frr defaults traditional
hostname r4
!
interface r4-r3
 ip ospf cost 10
 ip ospf network point-to-point
!
interface r4-r5
 ip ospf cost 10
 ip ospf network point-to-point
!
router ospf
 ospf router-id 172.16.0.4
 passive-interface r4-h4
 network 10.0.34.0/30 area 0
 network 10.0.45.0/30 area 0
 network 192.168.4.0/24 area 0
!
line vty
!
