frr version 10.5
frr defaults traditional
hostname r6
!
interface r6-r5
 ip ospf cost 10
 ip ospf network point-to-point
!
interface r6-r1
 ip ospf cost 40
 ip ospf network point-to-point
!
router ospf
 ospf router-id 172.16.0.6
 passive-interface r6-h6
 network 10.0.56.0/30 area 0
 network 10.0.16.0/30 area 0
 network 192.168.6.0/24 area 0
!
line vty
!
