frr version 10.5
frr defaults traditional
hostname r3
!
router bgp 100
 bgp router-id 172.16.0.3
 no bgp ebgp-requires-policy
 neighbor 10.0.23.1 remote-as 100
 neighbor 10.0.13.1 remote-as 100
 neighbor 10.0.34.2 remote-as 200
 !
 address-family ipv4 unicast
  network 10.0.23.0/30
  network 10.0.13.0/30
  network 10.0.34.0/30
  network 192.168.3.0/24
  neighbor 10.0.23.1 activate
  neighbor 10.0.23.1 next-hop-self
  neighbor 10.0.13.1 activate
  neighbor 10.0.13.1 next-hop-self
  neighbor 10.0.34.2 activate
 exit-address-family
!
line vty
!
