frr version 10.5
frr defaults traditional
hostname r4
!
router bgp 200
 bgp router-id 172.16.0.4
 no bgp ebgp-requires-policy
 neighbor 10.0.45.2 remote-as 200
 neighbor 10.0.34.1 remote-as 100
 !
 address-family ipv4 unicast
  network 10.0.34.0/30
  network 10.0.45.0/30
  network 192.168.4.0/24
  neighbor 10.0.45.2 activate
  neighbor 10.0.45.2 next-hop-self
  neighbor 10.0.34.1 activate
 exit-address-family
!
line vty
!
