frr version 10.5
frr defaults traditional
hostname r5
!
router bgp 200
 bgp router-id 172.16.0.5
 no bgp ebgp-requires-policy
 neighbor 10.0.45.1 remote-as 200
 neighbor 10.0.56.2 remote-as 300
 !
 address-family ipv4 unicast
  network 10.0.45.0/30
  network 10.0.56.0/30
  network 192.168.5.0/24
  neighbor 10.0.45.1 activate
  neighbor 10.0.45.1 next-hop-self
  neighbor 10.0.56.2 activate
 exit-address-family
!
line vty
!
